version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 800
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 800
      runas: root